name: Spell Check
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spell Check
        uses: codespell-project/actions-codespell@v2
        with:
          skip: .git,*.png,*.jpg
